name: Deploy Web to GitHub Pages (PoC static)

on:
  push:
    branches: [main]
    paths:
      - "apps/web/**"
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Verify static files exist
        run: |
          test -f apps/web/index.html
          test -f apps/web/data/fixed/manifest.json

      - name: Upload artifact (apps/web/)
        uses: actions/upload-pages-artifact@v3
        with:
          path: apps/web

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
